"""updated shared_with_user_id

Revision ID: 467b92a51617
Revises: d71733eb7173
Create Date: 2024-05-24 11:12:43.889388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = '467b92a51617'
down_revision = 'd71733eb7173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    foreign_keys = inspector.get_foreign_keys('shares')
    
    # Find the correct constraint name
    fk_name_to_drop = None
    for fk in foreign_keys:
        if 'shared_with_user_id' in fk['constrained_columns']:
            fk_name_to_drop = fk['name']
            break

    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_with_user_email', sa.String(), nullable=False))
        if fk_name_to_drop:
            batch_op.drop_constraint(fk_name_to_drop, type_='foreignkey')
        batch_op.create_foreign_key('fk_shares_shared_with_user_email', 'users', ['shared_with_user_email'], ['email'])
        batch_op.drop_column('shared_with_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    foreign_keys = inspector.get_foreign_keys('shares')
    
    # Find the correct constraint name
    fk_name_to_drop = None
    for fk in foreign_keys:
        if 'shared_with_user_email' in fk['constrained_columns']:
            fk_name_to_drop = fk['name']
            break

    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_with_user_id', sa.INTEGER(), nullable=False))
        if fk_name_to_drop:
            batch_op.drop_constraint(fk_name_to_drop, type_='foreignkey')
        batch_op.create_foreign_key('fk_shares_shared_with_user_id', 'users', ['shared_with_user_id'], ['id'])
        batch_op.drop_column('shared_with_user_email')

    # ### end Alembic commands ###
