"""added folder_id in starred_items and trash_items table

Revision ID: 538a6f02b505
Revises: 97735b4e234a
Create Date: 2024-05-18 19:33:59.601665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538a6f02b505'
down_revision = '97735b4e234a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starred_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_id', sa.Integer(), nullable=True))
        batch_op.alter_column('file_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(
            constraint_name='fk_starred_items_folder_id', 
            referent_table='folders', 
            local_cols=['folder_id'], 
            remote_cols=['id']
        )

    with op.batch_alter_table('trash_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_id', sa.Integer(), nullable=True))
        batch_op.alter_column('file_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(
            constraint_name='fk_trash_items_folder_id', 
            referent_table='folders', 
            local_cols=['folder_id'], 
            remote_cols=['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trash_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_trash_items_folder_id', type_='foreignkey')
        batch_op.alter_column('file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('folder_id')

    with op.batch_alter_table('starred_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_starred_items_folder_id', type_='foreignkey')
        batch_op.alter_column('file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('folder_id')