"""added image_url

Revision ID: 68423aca8021
Revises: d3317dd9ea45
Create Date: 2024-05-10 13:00:59.083954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68423aca8021'
down_revision = 'd3317dd9ea45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=100)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
