"""added created_at

Revision ID: d71733eb7173
Revises: 307cbc6ee6d7
Create Date: 2024-05-21 16:23:19.303431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71733eb7173'
down_revision = '307cbc6ee6d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
